# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@master
      - name: Get Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
         export PYTHONPATH=src
         coverage run src/tests.py
      - name: Tests report
        run: coverage report
