# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku
env:
  APPLICATION_NAME: "MyApp"
  PACKAGE_NAME: "fastapi-deploy-ver-${{ github.sha }}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
         pip install unittest
         unittest tests.py
